### ISSUE TITLE
简介部分的部分支例代码末尾有不匹配的括号

### ISSUE THREAD

**Issue by myfreess** [guenchi/AISI#2]

**Comment by include-yy** [comment]
了解了，我最近会改掉。上学期真的忙啊.
暑假期间我争取把整个内容翻译完。并润下笔

**Comment by include-yy** [comment]
没想到还真的有人看，^_^，我认为能接触到scheme的人都应该有阅读英文的能力了，感觉有些白费劲，不过，既然有人看，我这个暑假一定要有所作为

**Comment by myfreess** [comment]
pr到货了：/ @include-yy

**Comment by myfreess** [comment]
啊，因为我是看王垠大仙的软文入坑的，所以真d不会英文：/

感觉Scheme中文群组的人很友好(我问awk的问题都有人帮忙)，几本中文书也够看了，所以断断续续学了两个月：✓

谢谢你的翻译！@include-yy

**Comment by include-yy** [comment]
哈哈，你也受了王垠的影响啊

**Comment by include-yy** [comment]
能有所帮助当然很好，这也是我一开始想要搞点小翻译的原因

**Comment by guenchi** [comment]
> 没想到还真的有人看，^_^，我认为能接触到scheme的人都应该有阅读英文的能力了，感觉有些白费劲，不过，既然有人看，我这个暑假一定要有所作为

当然会有人看

**Comment by myfreess** [comment]
阅读设备可能有点老旧，甚至让人笑出声：✓
![AISI](https://github.com/myfreess/TermuxHiking/blob/master/Note/Graph/AISI.jpg)
@include-yy

**Comment by include-yy** [comment]
哈哈，我之前也用
